name: Deploy to REG.ru

on:
  push:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - nane: Login in server
        run: ssh root@31.31.199.129

#      - name: Check Docker-compose
#        run: apt-get install docker-compose
